default_agent: mcp_agentrock_basic_server
agents:
  mcp_agentrock_basic_server:
    name: mcp_agentrock_basic_server
    entrypoint: mcp_agentrock_basic_server.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::301581146302:role/agentcore-runtime-execution-role-agentcore_babbel_data_team
      execution_role_auto_create: true
      account: '301581146302'
      region: us-east-1
      ecr_repository: 301581146302.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-mcp_agentrock_basic_server
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: mcp_agentrock_basic_server-r9jEKOHcJ5
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:301581146302:runtime/mcp_agentrock_basic_server-r9jEKOHcJ5
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_MLKS5EUVq/.well-known/openid-configuration
        allowedClients:
        - 1v57ncpgu61qjgb8fi9h8ksphf
    oauth_configuration: null
