default_agent: agent_example
agents:
  agent_example:
    name: agent_example
    entrypoint: agent_example.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::301581146302:role/agentcore-runtime-execution-role-agentcore_babbel_data_team
      execution_role_auto_create: true
      account: '301581146302'
      region: us-east-1
      ecr_repository: bedrock-agentcore-data
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
